# Generated by Django 4.2.16 on 2024-10-27 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventovenue",
            name="agregado",
        ),
        migrations.RemoveField(
            model_name="eventovenue",
            name="descuento_porcentaje",
        ),
    ]
