# Generated by Django 4.2.16 on 2024-10-26 17:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_remove_actividadesrechazadas_actividad_and_more"),
        ("actividades", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="grupo",
            name="actividad",
        ),
        migrations.RemoveField(
            model_name="grupo",
            name="usuarios",
        ),
        migrations.AddField(
            model_name="actividad",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="actividad",
            name="fecha_creacion",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="actividad",
            name="fecha_eliminacion",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="actividad",
            name="fecha_modificacion",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="actividad",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="actividades/"),
        ),
        migrations.AlterField(
            model_name="calificacionactividad",
            name="actividad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calificaciones_actividad_actividades",
                to="actividades.actividad",
            ),
        ),
        migrations.AlterField(
            model_name="calificacionactividad",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calificaciones_actividad_usuarios",
                to="usuarios.usuario",
            ),
        ),
        migrations.DeleteModel(
            name="ActividadesRechazadas",
        ),
        migrations.DeleteModel(
            name="Grupo",
        ),
        migrations.AddField(
            model_name="actividad",
            name="tags",
            field=models.ManyToManyField(
                related_name="actividades", to="actividades.tag"
            ),
        ),
    ]
