# Generated by Django 4.2.16 on 2024-10-26 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "actividades",
            "0002_tag_remove_grupo_actividad_remove_grupo_usuarios_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="CalificacionActividad",
        ),
    ]
