# Generated by Django 4.2.16 on 2024-10-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("menus", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promocion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=100)),
                ("precio_final", models.DecimalField(decimal_places=2, max_digits=10)),
                ("menuitems", models.ManyToManyField(to="menus.menuitem")),
            ],
        ),
    ]
