# Generated by Django 4.2.16 on 2024-10-26 23:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("actividades", "0003_delete_calificacionactividad"),
        ("usuarios", "0002_remove_actividadesrechazadas_actividad_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="actividades_me_gustan",
            field=models.ManyToManyField(
                related_name="usuarios_me_gustan", to="actividades.actividad"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="fecha_creacion",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usuario",
            name="fecha_eliminacion",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="fecha_modificacion",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="foto_perfil",
            field=models.ImageField(blank=True, null=True, upload_to="usuarios/"),
        ),
    ]
