# Generated by Django 4.2.16 on 2024-10-27 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actividades", "0003_delete_calificacionactividad"),
        (
            "usuarios",
            "0003_usuario_actividades_me_gustan_usuario_fecha_creacion_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_login", models.DateField(auto_now_add=True)),
                (
                    "dispositivo",
                    models.CharField(
                        choices=[("movil", "Movil"), ("web", "Web")], max_length=20
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="usuario",
            name="actividades_spontime_activo",
            field=models.ManyToManyField(
                related_name="actividades_activas_usuario", to="actividades.actividad"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="estado_civil",
            field=models.CharField(
                blank=True,
                choices=[
                    ("soltero", "Soltero"),
                    ("casado", "Casado"),
                    ("es_complicado", "Es complicado"),
                    ("en_relacion_abierta", "En relación abierta"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="fecha_nacimiento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="fecha_ultimo_evento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="genero",
            field=models.CharField(
                blank=True,
                choices=[
                    ("masculino", "Masculino"),
                    ("femenino", "Femenino"),
                    ("no_binario", "No binario"),
                    ("otro", "Otro"),
                    ("prefiero_no_decirlo", "Prefiero no decirlo"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="spontime_activo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usuario",
            name="tipo_16personalidades_A",
            field=models.CharField(
                blank=True,
                choices=[
                    ("introvertido", "Introvertido"),
                    ("extrovertido", "Extrovertido"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="tipo_16personalidades_B",
            field=models.CharField(
                blank=True,
                choices=[("sensorial", "Sensorial"), ("intuitivo", "Intuitivo")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="tipo_16personalidades_C",
            field=models.CharField(
                blank=True,
                choices=[("pensamiento", "pensamiento"), ("emocional", "emocional")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="tipo_16personalidades_D",
            field=models.CharField(
                blank=True,
                choices=[("calificador", "calificador"), ("perceptivo", "Perceptivo")],
                max_length=20,
                null=True,
            ),
        ),
    ]
