# Generated by Django 4.2.16 on 2024-10-27 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("actividades", "0003_delete_calificacionactividad"),
        ("usuarios", "0004_login_usuario_actividades_spontime_activo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="actividades_me_gustan",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="actividades_no_me_gustan",
        ),
        migrations.AddField(
            model_name="usuario",
            name="reputacion",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="usuario",
            name="username",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name="usuariosbloqueados",
            name="bloqueo_activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="usuariosbloqueados",
            name="fecha_desbloqueo",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="GustoActividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nivel_gusto", models.IntegerField(default=0)),
                (
                    "actividad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="actividades.actividad",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.usuario",
                    ),
                ),
            ],
            options={
                "unique_together": {("usuario", "actividad")},
            },
        ),
        migrations.AddField(
            model_name="usuario",
            name="gustos_actividades",
            field=models.ManyToManyField(
                related_name="usuarios_gustos",
                through="usuarios.GustoActividad",
                to="actividades.actividad",
            ),
        ),
    ]
