# Generated by Django 4.2.16 on 2024-10-26 23:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("grupos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calificaciongrupo",
            name="fecha",
        ),
        migrations.RemoveField(
            model_name="grupo",
            name="fecha",
        ),
        migrations.AddField(
            model_name="calificaciongrupo",
            name="fecha_creacion",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="grupo",
            name="fecha_creacion",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
