# Generated by Django 4.2.16 on 2024-10-26 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("usuarios", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("foto", models.ImageField(upload_to="items/")),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=100)),
                ("calificacion", models.FloatField(default=0.0)),
                ("latitud", models.CharField(max_length=255)),
                ("longitud", models.CharField(max_length=255)),
                (
                    "actividades",
                    models.ManyToManyField(
                        related_name="venues", to="usuarios.actividad"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Promocion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("rebaja", "Rebaja"),
                            ("combo", "Combo"),
                            ("rebaja_total", "Rebaja a toda la carta"),
                            ("happy_hour", "Happy Hour"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descripcion", models.TextField()),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                (
                    "elementos_menu",
                    models.ManyToManyField(
                        related_name="promociones", to="comercios.menu"
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comercios.venue",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="menu",
            name="comercio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="comercios.venue"
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="menu_items",
            field=models.ManyToManyField(related_name="menus", to="comercios.menuitem"),
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(auto_now_add=True)),
                ("nombre", models.CharField(max_length=100)),
                (
                    "asistentes",
                    models.ManyToManyField(
                        related_name="eventos_asistentes", to="usuarios.usuario"
                    ),
                ),
                (
                    "comercio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comercios.venue",
                    ),
                ),
                (
                    "invitados",
                    models.ManyToManyField(
                        related_name="eventos_invitados", to="usuarios.usuario"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CalificacionGenerica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puntuacion", models.IntegerField()),
                ("fecha", models.DateField(auto_now_add=True)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.usuario",
                    ),
                ),
            ],
        ),
    ]
