# Generated by Django 4.2.16 on 2024-10-26 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0001_initial"),
        ("comercios", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="comercio",
        ),
        migrations.RemoveField(
            model_name="menu",
            name="menu_items",
        ),
        migrations.AddField(
            model_name="venue",
            name="menu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="menus.menu",
            ),
        ),
        migrations.AlterField(
            model_name="promocion",
            name="elementos_menu",
            field=models.ManyToManyField(related_name="promociones", to="menus.menu"),
        ),
        migrations.DeleteModel(
            name="CalificacionGenerica",
        ),
        migrations.DeleteModel(
            name="Menu",
        ),
        migrations.DeleteModel(
            name="MenuItem",
        ),
    ]
