# Generated by Django 4.2.16 on 2024-10-26 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comercios", "0002_remove_menu_comercio_remove_menu_menu_items_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Evento",
        ),
    ]
