# Generated by Django 4.2.16 on 2024-10-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actividades", "0001_initial"),
        ("comercios", "0003_delete_evento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="actividades",
            field=models.ManyToManyField(
                related_name="venues", to="actividades.actividad"
            ),
        ),
    ]
