# Generated by Django 4.2.16 on 2024-10-26 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "usuarios",
            "0003_usuario_actividades_me_gustan_usuario_fecha_creacion_and_more",
        ),
        ("actividades", "0003_delete_calificacionactividad"),
        ("calificaciones", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalificacionActividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puntuacion", models.IntegerField()),
                ("fecha", models.DateField(auto_now_add=True)),
                (
                    "actividad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calificaciones_actividad_actividades",
                        to="actividades.actividad",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calificaciones_actividad_usuarios",
                        to="usuarios.usuario",
                    ),
                ),
            ],
        ),
    ]
