# Generated by Django 4.2.16 on 2024-10-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promociones", "0001_initial"),
        ("menus", "0001_initial"),
        ("pedido", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="items_pedido",
            field=models.ManyToManyField(blank=True, to="menus.menuitem"),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="items_promocion",
            field=models.ManyToManyField(blank=True, to="promociones.promocion"),
        ),
    ]
